allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  netlify-cli: true
  sharp: true
  unix-dgram: true

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - netlify-cli
  - sharp
  - unix-dgram
