name: 'Install Playwright browsers'
description: 'Installs Playwright browsers.'
runs:
  using: 'composite'
  steps:
    - name: Install Playwright browsers
      run: pnpm exec playwright install --with-deps
      shell: bash
